#!/bin/sh

command="build"
if [ "$#" -ne "0" ]
then
	case "$1" in
	-*)
		;;
	*)
		command="$1"
		shift
	esac
fi

set -e
cd "`dirname "$0"`/objunhide"
cargo build --release
git submodule update --init --recursive
cd ../deno/cli
exec "../../scripts/cargo" "$command" "$@"
