#!/bin/sh

sep="--"
for arg in "$@"
do
	if [ "$arg" = "--" ]
	then
		sep=""
		break
	fi
done

set -e
cd "`dirname "$0"`/../deno/cli"
cargo clean
cargo rustc "$@" $sep -Clink-arg=-Wl,--hash-style=both
cp ../target/*/deno "$OLDPWD/deno_baseline"
cargo clean
