#!/bin/sh

if [ "$#" -lt "1" -o "$#" -gt "2" ]
then
	echo "USAGE: $0 <outfile> [deno]"
	exit 1
fi

outfile="$1"
if [ -e "$outfile" ]
then
	echo "$outfile: Already exists!" >&2
	exit 2
fi

deno="$2"
if [ -z "$deno" ]
then
	deno="$mydir/../deno/target/release/deno"
fi
if [ ! -e "$deno" ]
then
	echo "$deno: Not there!" >&2
	exit 3
fi

sample() {
	local stats="`time -f"%U,%S,%e,%M,%F,%R" "$@" 2>&1`"
	local mbs="$((`echo "$stats" | cut -d, -f4`/1024))"
	local pfs="`echo "$stats" | cut -d, -f5-`,$((`echo "$stats" | cut -d, -f5- | tr , +`))"
	printf "%s,%s,%s\n" "`echo "$stats" | cut -d, -f-3`" "$mbs" "$pfs"
}

mydir="`dirname "$0"`"

# Warmup
sample "$deno" eval "" >/dev/null
sample "$mydir/run" "$deno" eval "" >/dev/null

git log --oneline --abbrev-commit --no-decorate -1 | tee "$outfile"
./ld.so --version | head -n1 | tee -a "$outfile"
printf "0," | tee -a "$outfile"
sample "$deno" eval "" | tee -a "$outfile"
for libsets in `seq 1 15`
do
	printf "%s," "$libsets" | tee -a "$outfile"
	LIBGOTCHA_NUMGROUPS="$libsets" sample "$mydir/run" "$deno" eval "" | tee -a "$outfile"
done
